-- ============================================================================
-- notificar_superadmins(): permisos explícitos en las dos bases
-- ============================================================================
-- OJO: esta migración hace cosas DISTINTAS en cada proyecto, porque partían de
-- estados distintos. Comprobado el 2026-08-26:
--
--   · portgo-pruebas: anon podía ejecutar las 30 funciones de public. El
--     REVOKE de abajo es el que cuenta; el GRANT es un no-op.
--   · PRODUCCION: ya estaba cerrado — anon solo alcanza 17 de 40 funciones y
--     ninguna peligrosa. Pero notificar_superadmins estaba revocada TAMBIEN
--     para `authenticated`, asi que ahi el REVOKE es el no-op y **el GRANT es
--     imprescindible**: sin el, los 21 sitios de js/ que llaman a la RPC
--     fallan con "permission denied" y los superadmins dejan de recibir
--     avisos de altas, cuentas nuevas, solicitudes e incidentes.
--
-- Por eso esta migracion tiene que aplicarse ANTES de desplegar el codigo.
--
-- La diferencia entre las dos bases no es que produccion se relajara: es que
-- preparar-pruebas.sh sembro el proyecto de pruebas sin replicar los REVOKE.
-- Conviene tenerlo presente — pruebas NO es un espejo fiel para nada que
-- dependa de permisos.
--
-- ── ¿El GRANT a authenticated debilita algo? No ────────────────────────────
-- La politica insertar_notificaciones ya permite a cualquier autenticado
-- escribir en notificaciones cuando puede_notificar(user_id) es cierto, y esa
-- funcion devuelve true si el destinatario es superadmin. O sea: un usuario
-- con sesion YA podia insertar notificaciones arbitrarias a los superadmins
-- directamente por la tabla — asi funcionaba el codigo anterior, por diseño.
-- El GRANT da la misma capacidad por un camino mas barato y transaccional.
--
-- ── Por que anon sigue fuera ───────────────────────────────────────────────
-- Postgres concede EXECUTE a PUBLIC en cada función nueva salvo que se revoque
-- a mano. Donde eso no se corrigió, las funciones de public quedan al alcance
-- del rol `anon`, es decir de cualquiera con la clave anon — que va en el
-- código del cliente y es pública por diseño.
--
-- Para casi todas da igual:
--
--   · Las 11 RPC de negocio (enviar_oferta, responder_oferta,
--     cancelar_reservacion, calificar_servicio, registrar_evidencias,
--     avanzar_tracking, abrir_expediente, solicitar_cancelacion,
--     responder_contraoferta, enviar_mensaje, cerrar_acuerdo) verifican
--     auth.uid() por dentro. Sin sesión es NULL y la llamada falla sola.
--   · Los ayudantes (is_superadmin, mi_nombre, puede_notificar,
--     participa_en_expediente) responden a partir de auth.uid(): anon obtiene
--     false o NULL.
--   · Las puras (tracking_pasos, tabla_recurso, version_al_menos...) no leen
--     ni escriben nada.
--   · arranque_app es pública A PROPOSITO: es el arranque del cliente movil y
--     tiene que responder ANTES del login. No se toca.
--
-- La excepción es notificar_superadmins(): es SECURITY DEFINER, escribe en
-- notificaciones, y es la unica que no comprueba en absoluto quien la llama.
-- Tal como está, cualquiera sin sesión puede insertar filas con titulo y
-- mensaje arbitrarios en la campana de todos los superadmins. Eso es spam, y
-- peor: es texto que un superadmin lee dentro de un panel en el que confia.
--
-- Solo la llaman usuarios con sesión iniciada (21 sitios en js/, todos tras
-- una acción de empresa o cliente autenticado), así que revocar a anon no
-- quita nada que se esté usando.
-- ============================================================================

REVOKE EXECUTE ON FUNCTION public.notificar_superadmins(text, text, text) FROM anon;

-- Se deja explícito lo que sí debe poder llamarla, para que no dependa del
-- valor por omisión de PUBLIC.
GRANT EXECUTE ON FUNCTION public.notificar_superadmins(text, text, text) TO authenticated;

-- ── PENDIENTE DE DECISION, NO SE TOCA AQUI ─────────────────────────────────
-- expire_stale_offers() tampoco comprueba al llamante y tambien es
-- SECURITY DEFINER, asi que anon puede ejecutarla. El riesgo es bajo: su
-- UPDATE solo alcanza ofertas con expira_en < NOW(), es decir las que ya
-- estaban vencidas de todos modos. No puede caducar una oferta viva. Lo unico
-- que abre es la posibilidad de provocar escrituras repetidas sin sesion.
-- Ningun cliente la llama hoy (grep sb.rpc en js/ solo devuelve
-- cerrar_acuerdo); la usaria el pg_cron de la migracion opcional.
--
--   REVOKE EXECUTE ON FUNCTION public.expire_stale_offers() FROM anon;
-- ============================================================================
